/* ==================================== Audit Log ======================================== *
 * Title: Root Layout for the Application
 * Author: Hashan
 * Updated on: 11 Dec 2023
 * Description: Contains All the major components of the application
/* ======================================================================================== */
"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Nav from "@/components/Nav";
import Provider from "@/components/Provider";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * RootLayout component
 *
 * @param children - The content to be rendered inside the layout
 * @returns The rendered layout
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // Render the HTML document
    <html lang="en">
      <body>
        <Provider>
        <div className="main">
          <div className="gradient" />
        </div>
        <main className="app">
          <Nav />
          {children}
        </main>
        </Provider>
      </body>
    </html>
  );
}
